name: southglos
channels:
  - conda-forge
dependencies:
  - contextily
  - geopandas
  - iris
  - jupyterlab
  - just
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pyyaml
  - rasterio
  - rasterstats
  - requests
  - rioxarray
  - scikit-learn
  - seaborn
  - umap-learn
  - xarray
